// ═══════════════════════════════════════════════════════
// CHAPTER SUMMARIES — God of War: Novelización
// ═══════════════════════════════════════════════════════

const chapterSummaries = [
    {
        chapter: 1,
        title: 'Capítulo 1 — La Cacería',
        summary: `<p><strong>Escenario:</strong> Bosque nevado de Midgard. Kratos y Atreus acechan un ciervo de dieciséis puntas.</p>
        <p><strong>Apertura:</strong> Atreus tiene el arco tensado, el corazón desbocado, la voz de Faye resonando en su memoria. Kratos le instruye en voz baja junto a su oído. El mundo se reduce al espacio entre la flecha y el hombro del animal.</p>
        <p><strong>Primer fallo:</strong> Atreus cierra los ojos sin querer y dispara antes de la señal. La flecha se desvía. Kratos explota — luego se fuerza a detenerse. Dan caza al ciervo siguiendo sus huellas. Kratos reconoce la habilidad del niño: «Tu madre te enseñó bien.»</p>
        <p><strong>Segunda oportunidad:</strong> En una cresta, Atreus ignora las instrucciones de Kratos y confía en el ritmo aprendido de Faye. La flecha acierta en el hombro. El ciervo cae herido pero vivo. Atreus siente triunfo; Kratos dice solo «Bien.»</p>
        <p><strong>El golpe de gracia:</strong> El ciervo yace vivo, sufriendo. Atreus se paraliza — la emoción le llena la garganta; ofrece el cuchillo a su padre esperando ser liberado. Kratos lo obliga a terminar el trabajo. La mano de Atreus tiembla. Kratos se agacha junto a él, envuelve su mano enorme sobre la del niño — y clava la hoja. La sangre les salpica la cara. Segundos de silencio.</p>
        <p><strong>El troll:</strong> El sotobosque explota. Un troll del bosque emerge — atraído por el olor de la sangre — tres veces la altura de Kratos, colmillos curvados. «Troll del bosque. Quédate detrás de mí.» El troll golpea el pecho de Kratos y los envía rodando hacia un hueco entre los árboles. <em>Fin del capítulo.</em></p>
        <p><strong>★★★ Síntesis temática:</strong> El capítulo establece la tesis de toda la obra en una sola escena de caza: Kratos y Atreus no saben hablar entre sí, pero deben depender el uno del otro. La madre ausente estructura todo — sus instrucciones guían la mano del niño; su compasión define su carácter; su recuerdo es el único terreno común entre padre e hijo.</p>`
    },
    {
        chapter: 2,
        title: 'Capítulo 2 — El Combate',
        summary: `<p><strong>Escenario:</strong> El mismo claro del bosque. El troll acaba de derribar a Kratos y robar el ciervo.</p>
        <p><strong>Lengua Antigua:</strong> El troll gruñe «Kjöt» (carne). Kratos no entiende — pregunta a Atreus de reojo. Atreus traduce. El troll reclama «¡No pertenecéis aquí!» y Atreus, asombrado de entenderlo, le responde directamente: «¡Sí pertenecemos!» Faye lo había preparado para este momento.</p>
        <p><strong>Primera vez del Hacha:</strong> Kratos extrae el Hacha de Leviatán de la eslinga, la carga de escarcha mediante un comando silencioso y la lanza. El hacha atraviesa el ciervo — congelándolo — y el troll lo suelta. Al impactar el suelo, la presa se hace añicos en cien pedazos. El troll ve el arma y la codicia. Kratos extiende la palma: el hacha regresa. El troll gira para enfrentarlo con nueva evaluación. La sonrisa de Kratos.</p>
        <p><strong>Secuencia del combate:</strong> El troll golpea a Kratos como a un muñeco. El hacha cae. Vuelve. El troll agarra su mango. Atreus busca un ángulo — Kratos: «¡No dispares!» Kratos puncha la mandíbula del troll. El troll aplasta a Kratos en el suelo con una sonrisa. Levanta una roca apuntando a Atreus. Atreus: «Estoy bien. ¡Mátalo!» — apunta al pecho. El troll carga a Kratos antes de que pueda disparar. Kratos golpea la garganta, salta, clava el hacha en el hombro. El troll agarra su cuello. Kratos alza el hacha y le hiende la cabeza. El troll cae.</p>
        <p><strong>El colapso:</strong> Silencio. Atreus grita y se lanza de rodillas sobre el cadáver del troll — cuchillo en mano, apuñalando repetidamente. «¡Esto es lo que te mereces!» Lágrimas. «El pensamiento de perder a su padre después de perder a su madre lo llevó a un lugar donde no podía contener sus emociones.» Kratos lo aleja por la cintura. «¡No eres nada!» — entre toses. Kratos lo toma por los hombros, lo obliga a mirarlo. Sin consuelo. Sin abrazo. Lo suelta para que enfunde el cuchillo.</p>
        <p><strong>El veredicto:</strong> «Lo hicimos.» — «No estás listo.» Atreus protesta: encontró al ciervo, lo disparó, se probó. Kratos: «No estás listo» (dos veces más, con gravedad final). Comerán tejón. Una patada al troll muerto, flatulencia, Atreus se pellizca la nariz. Kratos desaparece en el bosque. «Te lo voy a demostrar» — bajo el aliento.</p>
        <p><strong>★★★ Síntesis temática:</strong> El capítulo establece tres inversiones decisivas respecto a la cacería: (1) Atreus puede hacer algo que Kratos no puede — hablar con el mundo. (2) El miedo de Atreus no es a fallar: es a quedar solo. (3) La primera demostración de poder de Kratos (el hacha) llega para rescatar el ciervo, no para matar — y el ciervo se destruye de todas formas. El veredicto inexplicado clausura el capítulo con la misma ambigüedad que abrirá el siguiente.</p>`
    },
    {
        chapter: 3,
        title: 'Capítulo 3 — El Hogar',
        summary: `<p><strong>Regreso:</strong> Kratos y Atreus salen del bosque con un tejón muerto. Sobre el bosque, dos cuervos negros en formación de arco — Atreus los señala; Faye le había pedido que la avisara si alguna vez los veía. Kratos: «Déjalos.» Jöphie, el gyrfalcón de Faye (plumaje negro moteado, envergadura de dos metros), emerge del dosel y dispersa a los cuervos, posándose en un tocón. Ignora el brazo extendido de Atreus. «Solo iba a Madre.» La proximidad del troll al hogar inquieta a Kratos: nunca había pasado.</p>
        <p><strong>Noche en casa:</strong> Atreus asa el tejón ante el fuego; las llamas despiertan el recuerdo de la pira funeraria de Faye — linos blancos, las llamas consumiéndola. Recuerda haber dejado el cuchillo de Faye sobre su pecho; metió la mano en las llamas para recuperarlo, quemándose la palma. Kratos grita cuando el tejón se carboniza. Cenan en silencio. La tercera silla vacía junto a Kratos. «Es hora» — se retiran. Atreus, en la oscuridad frente a la cama half-vacía de sus padres, no puede dormir. Escucha la respiración forzada de Kratos. Pregunta: si Faye le enseñó que hay dioses buenos que cuidan a los humanos, ¿por qué dejaron a su madre sin protección? El agotamiento lo arrastra. Los brazos de Kratos golpean el aire — pesadilla.</p>
        <p><strong>Pesadilla de Kratos:</strong> Un Kratos sin barba, en ropas griegas, sostiene posición con las Blades of Chaos contra tres lobos gigantes: el negro de ojos verdes como alfa, el blanco y el gris. Detrás de ellos, una mujer con capa y capucha alza el brazo y los tres se lanzan. El lobo negro le desgarra el muslo. «¿QUIÉN ERES?» — y despierta. Sudor. Sol naciente. Atreus duerme. Por décadas había enterrado ese recuerdo. Ahora ha vuelto.</p>
        <p><strong>La mañana:</strong> Atreus pregunta: «Hice todo lo que me pediste. ¿Por qué no es suficiente?» Kratos: «Cediste el control.» Atreus: «¡El troll intentaba matarnos! Tú también te enfadas en combate.» Kratos: «La ira puede ser un arma... si la controlas. Tú claramente no puedes. Y te arriesgas a caer enfermo cada vez que tu ira te domina. No es la primera vez.» Atreus concede el episodio anterior. «Pero estoy listo.» «No lo estás.»</p>
        <p><strong>El Desconocido:</strong> Ramas crujiendo, luego un golpe sordo. Alas coriáceas despegando, chillido antinatural, más ramas partiéndose. Golpes atronadores en la puerta. Voz áspera: «¡Sal! Sé quién eres. Y lo que es más importante, ¡sé lo que eres!» Kratos esconde a Atreus bajo la trampa del suelo (bajo la alfombra de piel de oso negro, símbolo rúnico pintado en la trampilla, metro y medio de profundidad, arcón misterioso en un rincón). Asegura la puerta con travesaño. Contempla sacar el hacha. No lo hace. «Eso es lo que haría el viejo Kratos.» Abre la puerta.</p>
        <p><strong>★★★ Síntesis temática:</strong> El hogar, espacio que debería ser refugio, se convierte en el lugar donde todo lo que Kratos intentaba mantener separado converge: el pasado griego en la pesadilla, el mundo hostil nórdico en los cuervos y el Desconocido, el duelo de Atreus en la silla vacía. La decisión final — abrir la puerta sin el hacha — es la prueba más clara hasta ahora de que Kratos ha cambiado. O de que está intentando cambiar. El texto deja la diferencia sin resolver.</p>`
    },
];
