// ═══════════════════════════════════════════════════════
// CHAPTER SUMMARIES — God of War: Novelización
// ═══════════════════════════════════════════════════════

const chapterSummaries = [
    {
        chapter: 1,
        title: 'Capítulo 1 — La Cacería',
        summary: `<p><strong>Escenario:</strong> Bosque nevado de Midgard. Kratos y Atreus acechan un ciervo de dieciséis puntas.</p>
        <p><strong>Apertura:</strong> Atreus tiene el arco tensado, el corazón desbocado, la voz de Faye resonando en su memoria. Kratos le instruye en voz baja junto a su oído. El mundo se reduce al espacio entre la flecha y el hombro del animal.</p>
        <p><strong>Primer fallo:</strong> Atreus cierra los ojos sin querer y dispara antes de la señal. La flecha se desvía. Kratos explota — luego se fuerza a detenerse. Dan caza al ciervo siguiendo sus huellas. Kratos reconoce la habilidad del niño: «Tu madre te enseñó bien.»</p>
        <p><strong>Segunda oportunidad:</strong> En una cresta, Atreus ignora las instrucciones de Kratos y confía en el ritmo aprendido de Faye. La flecha acierta en el hombro. El ciervo cae herido pero vivo. Atreus siente triunfo; Kratos dice solo «Bien.»</p>
        <p><strong>El golpe de gracia:</strong> El ciervo yace vivo, sufriendo. Atreus se paraliza — la emoción le llena la garganta; ofrece el cuchillo a su padre esperando ser liberado. Kratos lo obliga a terminar el trabajo. La mano de Atreus tiembla. Kratos se agacha junto a él, envuelve su mano enorme sobre la del niño — y clava la hoja. La sangre les salpica la cara. Segundos de silencio.</p>
        <p><strong>El troll:</strong> El sotobosque explota. Un troll del bosque emerge — atraído por el olor de la sangre — tres veces la altura de Kratos, colmillos curvados. «Troll del bosque. Quédate detrás de mí.» El troll golpea el pecho de Kratos y los envía rodando hacia un hueco entre los árboles. <em>Fin del capítulo.</em></p>
        <p><strong>★★★ Síntesis temática:</strong> El capítulo establece la tesis de toda la obra en una sola escena de caza: Kratos y Atreus no saben hablar entre sí, pero deben depender el uno del otro. La madre ausente estructura todo — sus instrucciones guían la mano del niño; su compasión define su carácter; su recuerdo es el único terreno común entre padre e hijo.</p>`
    },
    {
        chapter: 2,
        title: 'Capítulo 2 — El Combate',
        summary: `<p><strong>Escenario:</strong> El mismo claro del bosque. El troll acaba de derribar a Kratos y robar el ciervo.</p>
        <p><strong>Lengua Antigua:</strong> El troll gruñe «Kjöt» (carne). Kratos no entiende — pregunta a Atreus de reojo. Atreus traduce. El troll reclama «¡No pertenecéis aquí!» y Atreus, asombrado de entenderlo, le responde directamente: «¡Sí pertenecemos!» Faye lo había preparado para este momento.</p>
        <p><strong>Primera vez del Hacha:</strong> Kratos extrae el Hacha de Leviatán de la eslinga, la carga de escarcha mediante un comando silencioso y la lanza. El hacha atraviesa el ciervo — congelándolo — y el troll lo suelta. Al impactar el suelo, la presa se hace añicos en cien pedazos. El troll ve el arma y la codicia. Kratos extiende la palma: el hacha regresa. El troll gira para enfrentarlo con nueva evaluación. La sonrisa de Kratos.</p>
        <p><strong>Secuencia del combate:</strong> El troll golpea a Kratos como a un muñeco. El hacha cae. Vuelve. El troll agarra su mango. Atreus busca un ángulo — Kratos: «¡No dispares!» Kratos puncha la mandíbula del troll. El troll aplasta a Kratos en el suelo con una sonrisa. Levanta una roca apuntando a Atreus. Atreus: «Estoy bien. ¡Mátalo!» — apunta al pecho. El troll carga a Kratos antes de que pueda disparar. Kratos golpea la garganta, salta, clava el hacha en el hombro. El troll agarra su cuello. Kratos alza el hacha y le hiende la cabeza. El troll cae.</p>
        <p><strong>El colapso:</strong> Silencio. Atreus grita y se lanza de rodillas sobre el cadáver del troll — cuchillo en mano, apuñalando repetidamente. «¡Esto es lo que te mereces!» Lágrimas. «El pensamiento de perder a su padre después de perder a su madre lo llevó a un lugar donde no podía contener sus emociones.» Kratos lo aleja por la cintura. «¡No eres nada!» — entre toses. Kratos lo toma por los hombros, lo obliga a mirarlo. Sin consuelo. Sin abrazo. Lo suelta para que enfunde el cuchillo.</p>
        <p><strong>El veredicto:</strong> «Lo hicimos.» — «No estás listo.» Atreus protesta: encontró al ciervo, lo disparó, se probó. Kratos: «No estás listo» (dos veces más, con gravedad final). Comerán tejón. Una patada al troll muerto, flatulencia, Atreus se pellizca la nariz. Kratos desaparece en el bosque. «Te lo voy a demostrar» — bajo el aliento.</p>
        <p><strong>★★★ Síntesis temática:</strong> El capítulo establece tres inversiones decisivas respecto a la cacería: (1) Atreus puede hacer algo que Kratos no puede — hablar con el mundo. (2) El miedo de Atreus no es a fallar: es a quedar solo. (3) La primera demostración de poder de Kratos (el hacha) llega para rescatar el ciervo, no para matar — y el ciervo se destruye de todas formas. El veredicto inexplicado clausura el capítulo con la misma ambigüedad que abrirá el siguiente.</p>`
    },
    {
        chapter: 3,
        title: 'Capítulo 3 — El Hogar',
        summary: `<p><strong>Regreso:</strong> Kratos y Atreus salen del bosque con un tejón muerto. Sobre el bosque, dos cuervos negros en formación de arco — Atreus los señala; Faye le había pedido que la avisara si alguna vez los veía. Kratos: «Déjalos.» Jöphie, el gyrfalcón de Faye (plumaje negro moteado, envergadura de dos metros), emerge del dosel y dispersa a los cuervos, posándose en un tocón. Ignora el brazo extendido de Atreus. «Solo iba a Madre.» La proximidad del troll al hogar inquieta a Kratos: nunca había pasado.</p>
        <p><strong>Noche en casa:</strong> Atreus asa el tejón ante el fuego; las llamas despiertan el recuerdo de la pira funeraria de Faye — linos blancos, las llamas consumiéndola. Recuerda haber dejado el cuchillo de Faye sobre su pecho; metió la mano en las llamas para recuperarlo, quemándose la palma. Kratos grita cuando el tejón se carboniza. Cenan en silencio. La tercera silla vacía junto a Kratos. «Es hora» — se retiran. Atreus, en la oscuridad frente a la cama half-vacía de sus padres, no puede dormir. Escucha la respiración forzada de Kratos. Pregunta: si Faye le enseñó que hay dioses buenos que cuidan a los humanos, ¿por qué dejaron a su madre sin protección? El agotamiento lo arrastra. Los brazos de Kratos golpean el aire — pesadilla.</p>
        <p><strong>Pesadilla de Kratos:</strong> Un Kratos sin barba, en ropas griegas, sostiene posición con las Blades of Chaos contra tres lobos gigantes: el negro de ojos verdes como alfa, el blanco y el gris. Detrás de ellos, una mujer con capa y capucha alza el brazo y los tres se lanzan. El lobo negro le desgarra el muslo. «¿QUIÉN ERES?» — y despierta. Sudor. Sol naciente. Atreus duerme. Por décadas había enterrado ese recuerdo. Ahora ha vuelto.</p>
        <p><strong>La mañana:</strong> Atreus pregunta: «Hice todo lo que me pediste. ¿Por qué no es suficiente?» Kratos: «Cediste el control.» Atreus: «¡El troll intentaba matarnos! Tú también te enfadas en combate.» Kratos: «La ira puede ser un arma... si la controlas. Tú claramente no puedes. Y te arriesgas a caer enfermo cada vez que tu ira te domina. No es la primera vez.» Atreus concede el episodio anterior. «Pero estoy listo.» «No lo estás.»</p>
        <p><strong>El Desconocido:</strong> Ramas crujiendo, luego un golpe sordo. Alas coriáceas despegando, chillido antinatural, más ramas partiéndose. Golpes atronadores en la puerta. Voz áspera: «¡Sal! Sé quién eres. Y lo que es más importante, ¡sé lo que eres!» Kratos esconde a Atreus bajo la trampa del suelo (bajo la alfombra de piel de oso negro, símbolo rúnico pintado en la trampilla, metro y medio de profundidad, arcón misterioso en un rincón). Asegura la puerta con travesaño. Contempla sacar el hacha. No lo hace. «Eso es lo que haría el viejo Kratos.» Abre la puerta.</p>
        <p><strong>★★★ Síntesis temática:</strong> El hogar, espacio que debería ser refugio, se convierte en el lugar donde todo lo que Kratos intentaba mantener separado converge: el pasado griego en la pesadilla, el mundo hostil nórdico en los cuervos y el Desconocido, el duelo de Atreus en la silla vacía. La decisión final — abrir la puerta sin el hacha — es la prueba más clara hasta ahora de que Kratos ha cambiado. O de que está intentando cambiar. El texto deja la diferencia sin resolver.</p>`
    },
    {
        chapter: 4,
        title: 'Capítulo 4 — El Desconocido',
        summary: `<p><strong>El encuentro:</strong> Kratos sale con los puños plantados en las caderas. El Desconocido: sin camisa, tatuajes rúnicos, trenzas con cuentas en la barba castaña, ropa andrajosa, mirada sin alma, dedos en puños de forma refleja. «Pensé que serías más grande. Pero tú eres definitivamente el indicado.» / «Estás muy lejos de casa, ¿verdad?» — sabe que es un dios extranjero. Kratos: «¿Qué quieres?» / «Vete.» El Desconocido lo insulta («cobarde patético») y avanza tres pasos hasta quedar al alcance. Le da una bofetada.</p>
        <p><strong>El voto:</strong> Kratos absorbe el golpe. Recuerda el voto que hizo cuando llegó a esta tierra. Se fuerza a mantener los brazos a los lados — el fuego nace en sus ojos. «La rabia a la que juró que nunca volvería.» El Desconocido: «Tendrás que matarme para que eso suceda.» Serie de puñetazos. Kratos atrapa el cuarto: «Te avisé.»</p>
        <p><strong>El combate:</strong> El Desconocido envía a Kratos volando con un uppercut — sobre el tejado de la casa. Lo agarra, salta, lo estrella en el alero. A horcajadas, lluvia de golpes. Mira por el agujero del techo: «¿Por qué hay dos camas?» Kratos le golpea la mandíbula, lo tira del tejado. Kratos lanza el hacha cargada de escarcha — se clava en el pecho del Desconocido. No se congela. La herida se cierra en segundos. El Desconocido levanta un peñasco enorme. Kratos le arranca un tronco y lo bate de vuelta. Terminan junto a un monolito tallado colosal. Kratos lo vuelca sobre el Desconocido. Pausa. El monolito truena — el Desconocido lo levanta sonriendo: «Odín me envió por respuestas, pero tu vanidad lo convirtió en batalla.» Se arrojan el monolito mutuamente. La tierra cede — caen a una grieta. «No puedo sentir nada de esto.» Ríe. Uppercut. Kratos al fondo.</p>
        <p><strong>El final:</strong> Kratos emerge con brazos temblorosos. Carga, inmoviliza al Desconocido en llave de cuello inversa, le rompe el cuello. El cuerpo colapsa. Lo arroja a la grieta. Espera minutos. No vuelve. Kratos regresa a la casa. «¿Cómo supo de mí y de mi pasado? ¿Cómo me encontró después de todo este tiempo?»</p>
        <p><strong>★★★ Síntesis temática:</strong> El capítulo transforma la escala de la historia en dos golpes simultáneos: (1) el voto de Kratos — su promesa de cambio — se prueba y resiste hasta el último momento posible antes de ceder; (2) Odín ya sabe que existe. El tiempo de la invisibilidad ha terminado. Y el Desconocido, con su única pregunta «¿por qué hay dos camas?», convierte a Atreus de secreto familiar en objetivo potencial. El combate destruye el jardín de Faye — el último espacio de paz del hogar.</p>`
    },
    {
        chapter: 5,
        title: 'Capítulo 5 — La Partida',
        summary: `<p><strong>La casa dañada:</strong> Kratos recorre los daños (techo agujereado, paredes agrietadas, utensilios desperdigados). Patea una olla hacia la chimenea. Susurra: «Faye, ¿qué hago? Nuestro hijo no está listo para lo que nos pides... no sé cómo puedo hacer esto sin ti.» Abre la trampa del suelo. Atreus sale — pálido, con lágrimas secas — y sonríe aliviado al ver a su padre ileso. Kratos le ofrece la mano y lo sube de un tirón.</p>
        <p><strong>La partida:</strong> «Reúne tus cosas. Nos vamos ahora.» Atreus protesta: «¿Por qué nos vamos? Este es nuestro hogar.» Al empacar, saca las runestones de su madre — se desploma de rodillas. Kratos se suaviza al verlo. «¿Volveremos?» — sin respuesta directa. Kratos observa a su hijo en la puerta y se permite una sonrisa que borra de inmediato. «Pensé que no estabas listo.» — «No lo estás, pero ya no tenemos opción. Prueba que me equivoco.» Salen.</p>
        <p><strong>Afuera:</strong> Atreus ve la destrucción — imposible para un simple hombre. Piensa por primera vez que el visitante podría haber sido un dios. «Podrías haber muerto. No me dejes solo, ¿de acuerdo?» «Debemos seguir moviéndonos.» «¿Lo mataste?» — «Hice lo que debía.» Kratos mira el símbolo rúnico en la puerta por última vez: «Todo lo que había intentado construir le había sido arrebatado.» Se aleja.</p>
        <p><strong>En el camino:</strong> Atreus ve el bolso de cuero de Kratos — recuerda a su padre recogiendo las cenizas de Faye de la pira con sus propias manos. Casi cae por un precipicio distraído. Kratos lo agarra del cuello. «¿Puedo cargarlo yo?» — «¡No!» «¿A dónde vamos?» — Kratos señala el pico nevado en la distancia: «Allí es donde debemos ir.» ¿Cuánto tardará? No lo sabe. ¿Habrá gente? Sí. ¿Amigable? No. ¿Intentarán robarles? Posiblemente. «Debes estar preparado.»</p>
        <p><strong>El stave:</strong> Desde la cima de la colina, Atreus mira atrás. Los árboles dorados del bosque Iðunn forman, vistos desde arriba, la misma runa de protección de la puerta y la trampilla — pero del tamaño de un bosque entero. «Todo este tiempo ha habido un stave de protección alrededor de nuestro bosque.» Pausa. «El stave está roto allí.» Tres árboles faltantes. Los reconoce Kratos: eran los marcados con la huella de mano de Faye para la pira. Faye eligió ese emplazamiento. Faye marcó esos árboles. Faye sabía. Kratos: «¿A quién protegía? ¿A él? ¿A Atreus? ¿A sí misma?» Ahoga las emociones. «Ven. No hay vuelta atrás.» Siguen hacia el norte.</p>
        <p><strong>★★★ Síntesis temática:</strong> El cap. 5 cierra el prólogo de la historia y abre el viaje. Tres revelaciones simultáneas: (1) Kratos le habla a Faye — la armadura tiene grietas que Atreus no ve. (2) «Prueba que me equivoco» — el voto evoluciona hacia apertura explícita al hijo. (3) El stave de Faye — la madre no solo preparó a su hijo para el viaje; preparó el territorio, eligió la casa, marcó los árboles. Su muerte fue una decisión arquitectónica, no solo personal. Todo lo que creían saber de su vida en ese bosque era más grande de lo que veían.</p>`
    },
    {
        chapter: 6,
        title: 'Capítulo 6 — El Camino',
        summary: `<p><strong>En marcha:</strong> Con el hogar atrás y la montaña en el horizonte, Kratos y Atreus avanzan por el bosque de Midgard. La monotonía del viaje ya roe a Atreus — once inviernos de vida, la primera vez tan lejos de casa. Preguntarse cuánto tomará llegar no basta: tiene más preguntas que su padre tolerará. Las guarda.</p>
        <p><strong>Primera emboscada:</strong> Kratos se arrodilla de repente y arrastra a Atreus al suelo con un gesto. Nada visible. Nada audible. Luego: tres draugr irrumpen en el claro — escudos, lanzas, fuego ocrácea en sus venas. La orden: «Permanece listo detrás de mí.» Atreus dispara el primer flechazo — cuellos, no cabeza. El draugr tambalea y sigue. Kratos secciona, decapita, avanza. «¡Concéntrate, muchacho!» Dos draugr desvían su carga hacia el niño. Atreus rueda, se arrodilla, dispara limpio a la frente. Kratos lanza el hacha al segundo. El último draugr huye. Silencio. «¿Así estuvo bien?» Sin respuesta.</p>
        <p><strong>Lección táctica:</strong> En el camino que sigue, Kratos ofrece la primera instrucción de cooperación: «Si deseas ayudar, distrae a quien no sea mi objetivo. Pero solo cuando sea seguro.» / «Cronometra tus disparos. La velocidad cuesta precisión.» / «Piensa antes de actuar. Sabe lo que debes hacer antes de hacerlo.» Lecciones en movimiento, entre combates, al ritmo de la marcha.</p>
        <p><strong>Runas:</strong> Atreus detecta una roca taller que su padre cubierta de inscripciones: «Dice que hay un asentamiento Jötnar adelante.» — «¿Jötnar?» — «Gigantes.» Sigue caminando pensando en su madre — en cómo los llevaba de caza cerca, cómo su instinto detectaba el peligro antes de verlo, cómo nunca necesitaron combatir para volver a casa.</p>
        <p><strong>La caída:</strong> Un puente desvencijado de tablones podridos y cuerdas deshilachadas. Atreus corre hacia él. «¡Espera!» — demasiado tarde. Al décimo paso sin freno, el tablón se parte. La pierna derecha atraviesa la madera rota. Terror. «¡Padre, ayuda!» Kratos avanza sobre las cuerdas. Atreus intenta balancearse — el puente oscila violentamente. El soporte cede. Kratos se lanza. Agarra al niño en el aire. Absorbe el impacto de seis metros con el propio cuerpo. «¿Algo roto?» — «¡Estoy ileso!» — irritado. «Debes ir más despacio. Tu prisa nos costará.»</p>
        <p><strong>Draugr dormidos:</strong> El nivel inferior está sembrado de draugr inmóviles — ¿estatuas? ¿muertos? La calma baja la guardia de Atreus. Se acerca a uno a inspeccionarlo. «Muchacho...» El draugr salta a la vida. «¡No están muertos!» Combate explosivo: Kratos decapita tres con un arco y cercena el brazo del cuarto. Atreus falla el primer disparo, se tira al suelo, dispara desde las rodillas — limpio. Luego alcanza la espalda del draugr que ataca a su padre. Kratos clava el hacha en el pecho del último. «¿Era el último? ¿Estuve mejor?» — «Tómate aún más tiempo. No importa si disparas solo una vez. Muéstrame control.»</p>
        <p><strong>Losa del mercado:</strong> Junto al camino de salida, una losa de piedra cubierta de runas. Atreus: «Dice que hace mucho tiempo los Jötnar se reunían aquí para comerciar con los dioses. Este lugar era un mercado. ¿Crees que el propio Odín estuvo alguna vez aquí?» Kratos: «¿Tu madre habló de gigantes?» — «Me enseñó la palabra pero dijo poco de ellos.» — «¿Qué sabes de Odín?» — «Madre me habló del dios Odín muchas veces.» Un nuevo ruido detrás de las ruinas. «¡Algo se mueve!» — «Sígueme.»</p>
        <p><strong>Noche entre rocas:</strong> Kratos halla refugio entre formaciones escarpadas. Reparte la cena. Los pájaros cantan. «¿Le habló tu madre de un hombre que no siente dolor, que no puede ser matado?» — «Eso sería Baldur. Hijo de Odín.» — «¿Qué te dijo de Odín?» — «Gobierna los Æsir. Vive en Asgard.» Silencio largo. Atreus cae dormido. Kratos mira la luna llena casi completa. Piensa: Faye le enseñó sobre los dioses; él le enseñará a sobrevivir el mundo salvaje — y al mismo tiempo se enseñará a ser un buen padre. Ese pensamiento dispara imágenes de su propio padre. Las sacude. Solo un pensamiento puede dominar cada momento: mantener a su hijo a salvo. Se permite dormir.</p>
        <p><strong>★★★ Síntesis temática:</strong> El capítulo construye la interdependencia sin nombrarla: Atreus salva a Kratos en la primera emboscada; Kratos salva a Atreus en el puente. Los dos se necesitan antes de que cualquiera lo admita. La pregunta sobre Baldur es la primera fisura informativa de Kratos — sabe quién lo atacó y necesita confirmar el nombre, pero no comparte la hipótesis con el niño que duerme junto a él. El padre que «se enseñará a sí mismo» es la rendición más honesta hasta ahora: Kratos no sabe cómo hacer esto. Lo está aprendiendo en el mismo viaje.</p>`
    },

];
